version: '3'

services:

  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres-data-db:/var/lib/postgresql/data
    env_file:
      - envs/local/.env.db
    ports:
      - 5432:5432

  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: elenas_tasks
    container_name: django_app
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - envs/local/.env.app
      - envs/local/.env.db
    command: /start
    ports:
      - "8000:8000"

volumes:
  static_volume:
  media_volume: