version: '3'

services:

  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres-data-db:/var/lib/postgresql/data
    env_file:
      - envs/production/.env.db
    ports:
      - 5432:5432

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: elenas_tasks
    container_name: django_app
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - envs/production/.env.app
      - envs/production/.env.db
    command: /start

  nginx:
    restart: always
    container_name: nginx_server
    depends_on:
      - django
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./compose/production/nginx/certs:/etc/nginx/certs
    build:
      context: ./compose/production/nginx
    ports:
      - "443:443"
      - "80:80"

volumes:
  static_volume:
  media_volume: