HIGHEST_PRIORITY_TASK = "HIGHEST"
HIGH_PRIORITY_TASK = "HIGH"
MEDIUM_PRIORITY_TASK = "MEDIUM"
LOW_PRIORITY_TASK = "LOW"
LOWEST_PRIORITY_TASK = "LOWEST"

CHOICES_PRIORITY_TASKS = (
    (HIGHEST_PRIORITY_TASK, HIGHEST_PRIORITY_TASK),
    (HIGH_PRIORITY_TASK, HIGH_PRIORITY_TASK),
    (MEDIUM_PRIORITY_TASK, MEDIUM_PRIORITY_TASK),
    (LOW_PRIORITY_TASK, LOW_PRIORITY_TASK),
    (LOWEST_PRIORITY_TASK, LOWEST_PRIORITY_TASK)
)
